title:             개발자 김지식
email:             0921pig@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            김지식
baseurl:           ""
url:               "http://0921pig.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   0921pig
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
