title: Developer Dan
email: 0921pig@gmail.com
description: 안녕하세요. 안드로이드 및 서버 개발자 김지식 입니다.
baseurl:
url: ''
github_username: 0921pig
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
